### PR TITLE
fix access to Case/CaseActivity on WorlflowPanelPage

### PR DESCRIPTION
**Pull request by MehdyKarimpour**

### CODE REVIEW

**Comment by MehdyKarimpour** [comment]
Would you please merge this PR.

**Comment by MehdyKarimpour** [comment]
Yes, but do not undrestand why it happened.

**Comment by olmobrutall** [comment]
Make the pull request again an check the branches

**Comment by MehdyKarimpour** [comment]
Ok. I will do it when I was at office. Thanks.

**Pull request closed without merging**
